### ISSUE TITLE
Directory paths

### ISSUE THREAD

**Issue by angelocorbo** [Jefferson49/ExtendedImportExport#15]
Hi,

Trying to run the bash script and it's not clear what my version of " http://MY_URL/webtrees/index.php?route=/webtrees/ " should be, because my set up doesn't have a 'webtrees" directory but a "wt" instead.

Regardless, running it returns:

Resolving icorbus.com... 79.47.19.32
Connecting to icorbo.com|79.47.19.32|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-21 17:41:44 ERROR 404: Not Found.

Let me know what questions this raises,

Angelo C.

**Comment by Jefferson49** [comment]
Hello Angelo,

the route is: **BASE_URL**/index.php?route=/webtrees/DownloadGedcomWithURL

**BASE_URL** is defined in the **/data/config.ini.php** file in your webtrees installation. In the config.ini.php file, you will find a line:
**base_url="..."**

For example, if:
base_url="http://mysite.info/wt"
The DownloadGedcomWithURLoute will be:
http://mysite.info/wt/index.php?route=/webtrees/DownloadGedcomWithURL

**Comment by Jefferson49** [comment]
Hello Angelo, 

while working on another project, I recognized that the part of the URL with "route=/...." also changes if the base URL is changing. 

Regarding your installation path with "wt", you can try the following:

**BASE_URL**/index.php?route=/wt/DownloadGedcomWithURL

In the next release, I plan to provide better support for this feature. For example, a copy/paste option in the control panel, where the required URL can be obtained and copied.

**Comment by Jefferson49** [comment]
In module version v4.0.1, which has just been released, I added a view to **show the Remote URL** to be used for the specific webtrees installation **in the control panel**:

![url_for_remote_requests](https://github.com/user-attachments/assets/ee1caab3-723b-4acd-a3da-fcc0b731af94)
