### ISSUE TITLE
several

### ISSUE THREAD

**Issue by mariannevanharten** [Jefferson49/ExtendedImportExport#16]
Thanks for the new module!

I am missing some user defined Gedcom tags in the SCHMA section of the exported Gedcom file

In my exported Gedcom file I found some lines:
2 FORM image/tiffF
but I do not find what caused this?

Typo:
[Select GEDOM import/export/conversion/datafix](https://wezijnallemaalfamilie.nl/ExtendedImportExportSelection)
should be:
[Select GEDCOM import/export/conversion/datafix](https://wezijnallemaalfamilie.nl/ExtendedImportExportSelection)

Best regards,
Marianne

**Comment by Jefferson49** [comment]
Hello Marianne,

thank you for reporting the issues.

> In my exported Gedcom file I found some lines:
> 2 FORM image/tiffF
> but I do not find what caused this?

This is indeed a bug. Currently, TIF is converted before TIFF. Therefore, the last F in TIFF is not replaced. I have already fixed this. Will be included in the next release.

> Typo

Thanks. Also fixed.
